services:
  web:
    network_mode: host 
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: api_vuda
    restart: always
    env_file:
      - .env

    volumes:
      - ../src:/home/api_vuda
    command: flask run --host=0.0.0.0 --port=50000 --debug 
    ports:
      - 50000:50000